[package]
name = "with_google_bigquery2"
version = "0.1.0"
edition = "2021"

[dependencies]
google-bigquery2 = "5.0.3"

anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
